export const palabrasJuego = [
  "Playa",
  "Montaña",
  "Bosque",
  "Desierto",
  "Selva",
  "Isla",
  "Cueva",
  "Volcán",
  "Cascada",
  "Lago",
  "Río",
  "Glaciar",
  "Cañón",
  "Valle",
  "Acantilado",
  "Reserva Natural",
  "Parque",
  "Jardín Botánico",
  "Plaza",
  "Mercado",
  "Mercadillo",
  "Supermercado",
  "Centro Comercial",
  "Tienda de Ropa",
  "Librería",
  "Floristería",
  "Ferretería",
  "Taller Mecánico",
  "Gasolinera",
  "Peluquería",
  "Farmacia",
  "Restaurante",
  "Cafetería",
  "Pizzería",
  "Heladería",
  "Bar",
  "Discoteca",
  "Cine",
  "Teatro",
  "Museo",
  "Biblioteca",
  "Estadio",
  "Gimnasio",
  "Piscina",
  "Bolera",
  "Pista de Hielo",
  "Parque de Atracciones",
  "Circo",
  "Zoológico",
  "Acuario",
  "Sala de Conciertos",
  "Estudio de Grabación",
  "Estudio de Cine",
  "Escuela",
  "Instituto",
  "Universidad",
  "Hospital",
  "Clínica",
  "Consultorio Dental",
  "Comisaría",
  "Cuartel de Bomberos",
  "Juzgado",
  "Prisión",
  "Hotel",
  "Camping",
  "Cabaña",
  "Oficina",
  "Banco",
  "Fábrica",
  "Laboratorio",
  "Aeropuerto",
  "Estación de Tren",
  "Puerto",
  "Faro",
  "Puente",
  "Túnel",
  "Avión",
  "Tren",
  "Submarino",
  "Crucero",
  "Catedral",
  "Castillo",
  "Palacio",
  "Mansión",
  "Granja",
  "Viñedo",
  "Observatorio",
  "Planetario",
  "Pista de Esquí",
  "Cancha de Tenis",
  "Campo de Golf",
  "Oasis",
  "Duna",
  "Pradera",
  "Sabana",
  "Pantano",
  "Arrecife",
  "Bahía",
  "Golfo",
  "Península",
  "Archipiélago",
  "Mar",
  "Océano",
  "Sendero",
  "Mirador",
  "Parque Infantil",
  "Parque Acuático",
  "Paseo Marítimo",
  "Bazar",
  "Pastelería",
  "Carnicería",
  "Pescadería",
  "Frutería",
  "Juguetería",
  "Zapatería",
  "Joyería",
  "Óptica",
  "Papelería",
  "Estanco",
  "Mercería",
  "Tienda de Souvenirs",
  "Tienda de Muebles",
  "Tienda de Música",
  "Vinoteca",
  "Herbolario",
  "Quiosco",
  "Lavandería",
  "Tintorería",
  "Barbería",
  "Salón de Belleza",
  "Estudio de Tatuajes",
  "Estudio de Yoga",
  "Autolavado",
  "Clínica Veterinaria",
  "Taberna",
  "Cervecería",
  "Bar de Tapas",
  "Chiringuito",
  "Tetería",
  "Churrería",
  "Asador",
  "Coctelería",
  "Comedor",
  "Food Truck",
  "Auditorio",
  "Karaoke",
  "Campo de Fútbol",
  "Cancha de Baloncesto",
  "Polideportivo",
  "Pista de Patinaje",
  "Piscina Municipal",
  "Guardería",
  "Academia",
  "Conservatorio",
  "Escuela de Idiomas",
  "Escuela de Baile",
  "Centro de Salud",
  "Ayuntamiento",
  "Correos",
  "Embajada",
  "Consulado",
  "Albergue",
  "Casa Rural",
  "Apartamento Turístico",
  "Motel",
  "Estación de Autobuses",
  "Estación de Metro",
  "Parada de Autobús",
  "Helipuerto",
  "Aeródromo",
  "Teleférico",
  "Funicular",
  "Taxi",
  "Autobús",
  "Barco",
  "Ferry",
  "Metro",
  "Tranvía",
  "Garaje",
  "Nave Industrial",
  "Almacén",
  "Astillero",
  "Central Eléctrica",
  "Planta de Reciclaje",
  "Obra en Construcción",
  "Ruinas",
  "Anfiteatro",
  "Acueducto",
  "Muralla",
  "Torre",
  "Monumento",
  "Estatua",
  "Plaza de Toros",
  "Cementerio",
  "Convento",
  "Ermita",
  "Mezquita",
  "Sinagoga",
];
