export const palabrasJuego = [
  "Playa",
  "Montaña",
  "Hospital",
  "Escuela",
  "Restaurante",
  "Cine",
  "Biblioteca",
  "Parque",
  "Aeropuerto",
  "Museo",
  "Supermercado",
  "Gimnasio",
  "Oficina",
  "Teatro",
  "Zoológico",
  "Estadio",
  "Hotel",
  "Banco",
  "Tienda",
  "Café",
  "Jardín",
  "Plaza",
  "Mercado",
  "Piscina",
  "Circo",
  "Castillo",
  "Granja",
  "Prisión",
  "Universidad",
  "Catedral",
  "Submarino",
  "Tren",
  "Avión",
  "Barco",
  "Comisaría",
  "Consulado",
  "Casino",
  "Spa",
  "Crucero",
  "Base Militar",
  "Estudio de Cine",
  "Laboratorio",
  "Fábrica",
  "Estación Espacial",
  "Discoteca",
  "Bodega",
  "Lavandería",
  "Peluquería",
  "Tatuaje",
  "Funeral",
  "Boda",
  "Concierto",
  "Fiesta",
  "Campamento",
  "Cueva",
  "Desierto",
  "Selva",
  "Volcán",
  "Isla",
  "Puente",
  "Torre",
  "Faro",
  "Puerto",
  "Mina",
  "Mercadillo",
  "Carnaval",
  "Festival",
  "Iglesia",
  "Templo Islámico",
  "Templo",
  "Templo Judío",
  "Cementerio",
  "Casa de Niños",
  "Residencia",
  "Clínica",
  "Ambulancia",
  "Bomberos",
  "Juzgado",
  "Tribunal",
  "Congreso",
  "Palacio",
  "Mansión",
  "Cabaña",
  "Tienda de Campaña",
  "Autobus",
  "Metro",
  "Taxi",
  "Helicóptero",
  "Globo Aerostático",
  "Paracaídas",
  "Safari",
  "Acuario",
  "Planetario",
  "Observatorio",
  "Invernadero",
  "Viñedo",
  "Olivar",
  "Huerto",
  "Rancho",
  "Hacienda",
  "Fortaleza",
  "Búnker",
  "Cuartel",
  "Depósito de Armas",
  "Hipódromo",
  "Pista de Ciclismo",
  "Pista de Hielo",
  "Bolera",
  "Cancha de Tenis",
  "Campo de Golf",
  "Pista de Esquí",
  "Parque de Atracciones",
  "Montaña Rusa",
  "Noria",
  "Tiovivo",
  "Ruinas Romanas",
  "Anfiteatro",
  "Coliseo",
  "Pirámide",
  "Esfinge",
  "Monumento Alto",
  "Arco del Triunfo",
  "Estatua de la Libertad",
  "Torre Eiffel",
  "Big Ben",
  "Taj Mahal",
  "Gran Muralla",
  "Machu Picchu",
  "Stonehenge",
  "Petra",
  "Cristo Redentor",
  "Ópera de Sídney",
  "Burj Khalifa",
  "Sagrada Familia",
  "Alhambra",
  "Acueducto",
  "Molino",
  "Cascada",
  "Glaciar",
  "Cañón",
  "Valle",
  "Llanura",
  "Acantilado",
  "Arrecife",
  "Laguna",
  "Río",
  "Lago",
  "Pantano",
  "Manantial",
  "Fuente de Agua Caliente",
  "Oasis",
  "Duna",
  "Pradera",
  "Región Polar",
  "Sabana",
  "Jungla",
  "Bosque",
  "Bosque del Norte",
  "Pantano Tropical",
  "Coral",
  "Isla de Coral",
  "Península",
  "Cabo",
  "Bahía",
  "Estrecho",
  "Canal",
  "Golfo",
  "Mar",
  "Océano",
  "Iceberg",
  "Polo Norte",
  "Polo Sur",
  "Ecuador",
  "Trópico",
  "Continente",
  "Grupo de Islas",
  "Cosmos",
  "Galaxia",
  "Nebulosa",
  "Agujero Negro",
  "Asteroide",
  "Cometa",
  "Satélite",
  "Luna",
  "Sol",
  "Planeta",
  "Estrella",
  "Meteorito",
  "Eclipse",
  "Constelación",
  "Vía Láctea",
  "Sistema Solar",
  "Órbita",
  "Cohete",
  "Nave Espacial",
  "Astronauta",
  "Telescopio",
  "Antena Espacial",
  "Cráter",
  "Rover",
  "Colonia Espacial",
  "Estación Orbital",
  "Transbordador",
  "Capsula Espacial",
  "Traje Espacial",
  "Gravedad Cero",
  "Atmósfera",
  "Capa de Aire",
  "Aurora Boreal",
  "Aurora Austral",
  "Arcoíris",
  "Rayo",
  "Trueno",
  "Tormenta",
  "Huracán",
  "Tornado",
  "Ciclón",
  "Tifón",
  "Tsunami",
  "Terremoto",
  "Erupción",
  "Avalancha",
  "Alud",
  "Deslizamiento",
  "Inundación",
  "Sequía",
  "Incendio Forestal",
  "Ventisca",
  "Granizo",
  "Niebla",
  "Bruma",
  "Escarcha",
  "Rocío",
  "Nube",
  "Nubes Altas",
  "Nubes Bajas",
  "Panadería",
  "Carnicería",
  "Pescadería",
  "Floristería",
  "Ferretería",
  "Librería",
  "Joyería",
  "Zapatería",
  "Óptica",
  "Farmacia",
  "Gasolinera",
  "Taller Mecánico",
  "Pizzería",
  "Heladería",
  "Pastelería",
  "Cervecería",
  "Bar de Copas",
  "Taberna",
  "Pub",
  "Bar Típico",
  "Cantina",
  "Comedor",
  "Cafetería",
  "Tetería",
  "Juguetería",
  "Guardería",
  "Colegio",
  "Instituto",
  "Academia",
  "Conservatorio",
  "Escuela de Baile",
  "Dojo",
  "Ring de Boxeo",
  "Tatami",
  "Pabellón Deportivo",
  "Muro de Escalada",
  "Skatepark",
  "Marina",
  "Muelle",
  "Astillero",
  "Hangar",
  "Torre de Control",
  "Aduana",
  "Frontera",
  "Peaje",
  "Rotonda",
  "Cruce",
  "Semáforo",
  "Paso de Peatones",
  "Aparcamiento",
  "Garaje",
  "Túnel",
  "Viaducto",
  "Alcantarilla",
  "Planta de Agua",
  "Embalse",
  "Presa",
  "Central Eléctrica",
  "Molino de Viento",
  "Panel Solar",
  "Refinería",
  "Plataforma Petrolífera",
  "Cantera",
  "Serrería",
  "Corral",
  "Establo",
  "Gallinero",
  "Colmena",
  "Nido",
  "Madriguera",
  "Guarida",
  "Refugio",
  "Silo",
  "Almacén",
  "Contenedor",
  "Puerto de Carga",
  "Terminal",
  "Anden",
  "Vía de Tren",
  "Parada de Tren",
  "Tranvía",
  "Teleférico",
  "Funicular",
  "Ascensor",
  "Escalera Mecánica",
  "Pasillo",
  "Vestíbulo",
  "Recepción",
  "Sala de Espera",
  "Quirófano",
  "Sala de Urgencias",
  "UCI",
  "Maternidad",
  "Depósito de Cadáveres",
  "Archivo",
  "Biblioteca de Periódicos",
  "Videoteca",
  "Biblioteca de Música",
  "Museo de Pinturas",
  "Galería de Arte",
  "Sala de Exposiciones",
  "Estudio de Grabación",
  "Plató de Televisión",
  "Camerino",
  "Backstage",
  "Escenario",
  "Detrás del Escenario",
  "Patio de Butacas",
  "Palco",
  "Platea",
  "Anfiteatro Moderno",
  "Auditorio",
  "Sala de Conferencias",
  "Sala de Juntas",
  "Despacho",
  "Oficina Pequeña",
  "Open Space",
  "Coworking",
  "Centro de Empresas",
  "Aceleradora",
  "Empresa Tecnológica",
  "Nave Industrial",
  "Polígono Industrial",
  "Zona Comercial",
  "Parque Tecnológico",
  "Silicon Valley",
  "Centro Comercial",
  "Outlet",
  "Bazar",
  "Rastro",
  "Feria",
  "Exposición",
  "Salón",
  "Stand",
  "Quiosco",
  "Puesto Ambulante",
  "Food Truck",
  "Chiringuito",
  "Merendero",
  "Área de Servicio",
  "Mirador",
  "Mirador Panorámico",
  "Terraza",
  "Azotea",
  "Ático",
  "Sótano",
  "Bodega Subterránea",
  "Catacumbas",
  "Cripta",
  "Mausoleo",
  "Panteón",
  "Tumba",
  "Sarcófago",
  "Monumento",
  "Memorial",
  "Parque Nacional",
  "Reserva Natural",
  "Santuario",
  "Ermita",
  "Monasterio",
  "Convento",
  "Abadía",
  "Claustro",
  "Campanario",
  "Cripta Medieval",
  "Torre del Homenaje",
  "Muralla",
  "Almena",
  "Foso",
  "Puente Levadizo",
  "Muralla Defensiva",
  "Ciudadela",
  "Fortificación",
  "Fuerte",
  "Alcázar",
  "Torreón",
]
